name: Reusable deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the depl artifact files
        required: true
        default: dist
        type: string
    outputs:
      reuslt:
        description: The result of dep operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output
        run: echo "output"
      - name: Set Result Output
        id: set-result
        run: echo "step-result=seucess" >> $GitHub_OUTPUT

